"""
Developer credential storage and access.

SECURITY NOTE: These credentials are obfuscated for convenience only.
They are NOT cryptographically secure and can be reverse-engineered.
Do not commit plaintext credentials to version control.
"""

from .obfuscator import deobfuscate

# Obfuscated developer credentials (generated by tools/setup_dev_credentials.py)
# These are XOR'd with project key and stored as bytearrays
_DEV_ID_OBFUSCATED = bytearray([
    9, 23, 0, 20, 26, 22,
])

_DEV_PASSWORD_OBFUSCATED = bytearray([
    33, 4, 28, 16, 29, 29, 17, 35, 8, 75, 26,
])

# Version is used to construct softname
__version__ = "0.1.0"


def get_dev_credentials() -> dict:
    """
    Retrieve developer credentials for ScreenScraper API.
    
    Returns:
        Dictionary with devid, devpassword, and softname
        
    Raises:
        ValueError: If credentials are not initialized
    """
    if not _DEV_ID_OBFUSCATED or not _DEV_PASSWORD_OBFUSCATED:
        raise ValueError(
            "Developer credentials not initialized. "
            "Run tools/setup_dev_credentials.py to configure."
        )
    
    return {
        'devid': deobfuscate(_DEV_ID_OBFUSCATED),
        'devpassword': deobfuscate(_DEV_PASSWORD_OBFUSCATED),
        'softname': f'curateur_{__version__}'
    }
